name = "plasmic-img-optimizer"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[env.production]
name = "plasmic-img-optimizer"
route = { pattern = "img-optimizer.example.com/*", zone_name = "example.com" }

[env.production.vars]
RUST_LOG = "info"
CACHE_TTL = "86400"

[[kv_namespaces]]
binding = "IMAGE_CACHE"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"